#!/bin/bash
#SBATCH --mail-user=quanhu.sheng.1@vumc.org
#SBATCH --mail-type=FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=10:00:00
#SBATCH --mem=44G
#SBATCH --constraint=haswell
#SBATCH -o /scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/annotation_genes_locus/log/lindsay_exomeseq_3772_uniqueR.log

if [ -n "${SLURM_JOB_ID}" ] ; then
  smemwatch -k 99 -d 50 $$ &
fi






set -o pipefail

cd '/scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/annotation_genes_locus/result'


if [[ !(1 -eq $1) ]]; then
  if [[ ( -s /scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/annotation_genes_locus/result/lindsay_exomeseq_3772.bed ) || ( -d /scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/annotation_genes_locus/result/lindsay_exomeseq_3772.bed ) ]]; then
    echo job has already been done. if you want to do again, delete /scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/annotation_genes_locus/result/lindsay_exomeseq_3772.bed and submit job again.
    exit 0
  fi
fi

echo CQS::UniqueR_start=`date`
echo working in /scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/annotation_genes_locus/result ...
 

export R_LIBS=
export PYTHONPATH=
export JAVA_HOME=
 


singularity exec -c -B /gpfs23,/scratch,/gpfs52,/data,/home,/tmp -e /data/cqs/softwares/singularity/cqs-exomeseq.simg  bash /scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/annotation_genes_locus/pbs/lindsay_exomeseq_3772_uniqueR.pbs.sh 

echo CQS::UniqueR_end=`date`

exit 0

