#!/bin/bash
#SBATCH --mail-user=quanhu.sheng.1@vumc.org
#SBATCH --mail-type=FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=10:00:00
#SBATCH --mem=44G
#SBATCH --constraint=haswell
#SBATCH -o /scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/bwa_refine_nosoftclip_gatk4_CNV_Germline_03_FilterIntervals/log/lindsay_exomeseq_3772_fi.log

if [ -n "${SLURM_JOB_ID}" ] ; then
  smemwatch -k 99 -d 50 $$ &
fi






set -o pipefail

cd '/scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/bwa_refine_nosoftclip_gatk4_CNV_Germline_03_FilterIntervals/result'


if [[ !(1 -eq $1) ]]; then
  if [[ ( -s lindsay_exomeseq_3772.filtered.interval_list ) || ( -d lindsay_exomeseq_3772.filtered.interval_list ) ]]; then
    echo job has already been done. if you want to do again, delete /scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/bwa_refine_nosoftclip_gatk4_CNV_Germline_03_FilterIntervals/result/lindsay_exomeseq_3772.filtered.interval_list and submit job again.
    exit 0
  fi
fi

echo GATK4::FilterIntervals_start=`date`
echo working in /scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/bwa_refine_nosoftclip_gatk4_CNV_Germline_03_FilterIntervals/result ...
 

export R_LIBS=
export PYTHONPATH=
export JAVA_HOME=
 


singularity exec -c -B /gpfs23,/scratch,/gpfs52,/data,/home,/tmp -e /data/cqs/softwares/singularity/cqs-gatk4.simg  bash /scratch/cqs/shengq2/jennifer/20200407_lindsay_exomeseq_3772_hg38/bwa_refine_nosoftclip_gatk4_CNV_Germline_03_FilterIntervals/pbs/lindsay_exomeseq_3772_fi.pbs.sh 

echo GATK4::FilterIntervals_end=`date`

exit 0

